config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'home#index'
  resources :contacts
  resources :services, :only => [:index, :show]
  resources :products, :only => [:index, :show]
  resources :categories, :only => [:index, :show]
  
  

     get 'about' => 'home#about'

     

   

  

end

app/models/about_u.rb
class AboutU < ActiveRecord::Base
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

    before_save :check_about_u 

  # def check_about_u
  #   if AboutU.exists? 
  #   	about=AboutU.first
  #   	about.update_attributes(name: self.name, description: self.description)
  #   end
  # end

  # def check_about_u
  #   errors.add(:name, "You can create About U only one time") if AboutU.exists?
  # end 
  validates :name, :description, :avatar, :presence => true
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  has_many :products ,dependent: :destroy

  validates :name, :avatar, :presence => true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
	validates :name, :email, :phone, :message, :presence => true
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  belongs_to :category

  #validates_uniqueness_of :name, presence: true
  validates :name,:avatar, :presence => true
end

app/models/service.rb
class Service < ActiveRecord::Base
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

   validates :name,:avatar,:message, :presence => true
end

app/models/slider_image.rb
class SliderImage < ActiveRecord::Base
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  	validates :avatar, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  layout :choose_layout

    def after_sign_in_path_for(resource)
	    if current_admin
	      flash[:notice] = "Hello! Admin"
	      admin_root_path
	    end
	end

	  def choose_layout
	    if devise_controller? && current_admin

	      "admin/admin_layout"
	    else
	      "application"
	    end      
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to new_contact_path, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :email, :phone, :message)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
	  @slider_image=SliderImage.all
	end

	def about
	  @about_us = AboutU.all
	end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show]


  # GET /products/1
  # GET /products/1.json
  def show

  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show]

  # GET /services
  # GET /services.json
  def index
    @services = Service.all
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:name, :avatar, :message)
    end
end

app/helpers/admin/about_us_helper.rb
module Admin::AboutUsHelper
end

app/helpers/admin/contacts_helper.rb
module Admin::ContactsHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/admin/services_helper.rb
module Admin::ServicesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/contacts/_form.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <div class="row">
    <div class="col-sm-4">
      <h3>Contact Details</h3>
      <hr>
      <address>
        <strong>Email:</strong> <a href="mailto:#"> name@domain.com</a><br><br>
        <strong>Phone:</strong> (555)123-4567
        <br><br>
        <strong>address:</strong> maihar
      </address>
    </div>
      
      <div class="col-sm-8 contact-form">
        <%= form_for(@contact,url:{action: @contact.new_record? ? :create : :update}) do |f| %>
          <% if @contact.errors.any? %>
            <div id="error_explanation">
              <h2><%#= pluralize(@contact.errors.count, "error") %> <!-- prohibited this contactmin_contact from being saved: --></h2>

              <ul>
              <% @contact.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>
          <div class="row">
            <div class="col-xs-4 col-md-4 form-group">
              <%= f.label :name %>
              <%= f.text_field :name,:class=>"form-control",:placeholder=>"name" %>
            </div>
            <div class="col-xs-4 col-md-4 form-group">
              <%= f.label :email %>
              <%= f.text_field :email,:class=>"form-control",:placeholder=>"email" %>
            </div>
            <div class="col-xs-4 col-md-4 form-group">
              <%= f.label :phone %>
              <%= f.text_field :phone,:class=>"form-control",:placeholder=>"phone" %>
            </div>
          </div>
            <%= f.label :message %>
            <%= f.text_area :message,:class=>"form-control",:placeholder=>"message" %>
            <br />
          <div class="row">
            <div class="col-xs-12 col-md-12 form-group">
              <%= f.submit :class=>"btn btn-info btn-update"%>
            </div>
          </div>
        <% end %>
      </div>
  </div>
</div>

app/views/contacts/new.html.erb
<div id="page-content-wrapper">
  <div class="container-fluid">
		<%= render 'form' %>

		<%#= link_to 'Back', contacts_path,:class=>"btn btn-default" %>
	</div>
</div>

app/views/products/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <div class="row">

    <div class="col-md-4">
      <h3><%= @product.name %></h3>
          <%= image_tag @product.avatar,:style=>"width: 344px;"%>
    </div>

    <div class="col-md-8">
        <h3>Description</h3>
        <p><%= @product.description %></p>
    </div>

  </div><br>  
</div>

app/views/services/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
<% @services.each do |service| %>
  <div class="row">

    <div class="col-md-4">
      <h3><%= link_to service.name, service_path(service)%></h3>
        <%= link_to service_path(service) do %>
          <%= image_tag service.avatar.url(:thumb) %>
        <% end %>
    </div>

    <div class="col-md-8">
        <h3>Description</h3>
        <p><%= truncate("#{service.message}", :length => 250, :omission => '... (continued)') %></p>
    </div>

  </div><br>
<%end%>
  
</div>

app/views/services/show.html.erb
<div class="container">
	<p id="notice"><%= notice %></p>

	<div class="row">

		<div class="col-md-4">
			<h3><%= @service.name %></h3>
		    <%= image_tag @service.avatar.url,:class=>"img-responsive" %>
		</div>

		<div class="col-md-8">
		    <h3>Description</h3>
		    <p><%= @service.message %></p>
		</div>

	</div><br>

	<%= link_to 'Back', services_path,:class=>"btn btn-default" %>
</div>