config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'home#index'
  resources :contacts
  resources :services, :only => [:index, :show]
  resources :products, :only => [:index, :show]
  resources :categories, :only => [:index, :show]
  
  

     get 'about' => 'home#about'

     

   

  

end

app/models/about_u.rb
class AboutU < ActiveRecord::Base
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

    before_save :check_about_u 

  # def check_about_u
  #   if AboutU.exists? 
  #   	about=AboutU.first
  #   	about.update_attributes(name: self.name, description: self.description)
  #   end
  # end

  # def check_about_u
  #   errors.add(:name, "You can create About U only one time") if AboutU.exists?
  # end 
  validates :name, :description, :avatar, :presence => true
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  has_many :products ,dependent: :destroy

  validates :name, :avatar, :presence => true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
	validates :name, :email, :phone, :message, :presence => true
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  belongs_to :category

  #validates_uniqueness_of :name, presence: true
  validates :name,:avatar, :presence => true
end

app/models/service.rb
class Service < ActiveRecord::Base
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

   validates :name,:avatar,:message, :presence => true
end

app/models/slider_image.rb
class SliderImage < ActiveRecord::Base
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  	validates :avatar, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  layout :choose_layout

    def after_sign_in_path_for(resource)
	    if current_admin
	      flash[:notice] = "Hello! Admin"
	      admin_root_path
	    end
	end

	  def choose_layout
	    if devise_controller? && current_admin

	      "admin/admin_layout"
	    else
	      "application"
	    end      
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to new_contact_path, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :email, :phone, :message)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
	  @slider_image=SliderImage.all
	end

	def about
	  @about_us = AboutU.all
	end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show]


  # GET /products/1
  # GET /products/1.json
  def show

  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show]

  # GET /services
  # GET /services.json
  def index
    @services = Service.all
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:name, :avatar, :message)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name),:class=>"btn btn-default" %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/_footer.html.erb
<footer>
	<p>&copy; Company 2016</p>
</footer>

app/views/layouts/_head.html.erb
<head>
  <title>Astrology</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

app/views/layouts/_navbar.html.erb
<header>
  <div class="navbar navbar-default navbar-static-top">
    <div class="container">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path%>">Astrology</a>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
            <li>
                <a href="<%= about_path%>">About</a>
            </li>
            <li>
                <a href="<%= services_path%>">Services</a>
            </li>
            <li>
                <a href="<%= new_contact_path%>">Contact</a>
            </li>
            <li>
                <a href="<%= categories_path%>">Product</a>
            </li>
        </ul>
      </div>
    </div>
  </div>
</header>

app/views/layouts/admin/_footer.html.erb
<footer>
	<p>&copy; Company 2016</p>
</footer>

app/views/layouts/admin/_head.html.erb
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Astrology" %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
  </head>

app/views/layouts/admin/_navbar.html.erb
<header>
  <div class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <a href="#menu-toggle" class="fa fa-arrows-h navbar-brand" id="menu-toggle"></a>
          <a class="navbar-brand" href="<%= admin_root_path%>">Astrology</a>
            <ul class="nav navbar-nav navbar-right">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <i class="fa fa-user fa-fw"></i>
                <i class="fa fa-caret-down"></i>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Change password", edit_admin_registration_path %></li>
                  <li><%= link_to "Logout", destroy_admin_session_path, :method=> :delete %></li>
                </ul>
              </li>
            </ul>
    </div>
  </div>
</header>

app/views/layouts/admin/_sidebar.html.erb
<!-- Sidebar -->
<div id="sidebar-wrapper">
    <ul class="sidebar-nav">
        <li class="sidebar-brand">
            <a href="#">
                <a class="navbar-brand" href="<%#= root_path%>">Dashboard</a>
            </a>
        </li>
         <li>
            <a href="<%= admin_slider_images_path%>">SliderImage</a>
        </li>
        <li>
            <a href="<%= admin_contacts_path%>">Contact</a>
        </li>
        <li>
            <a href="<%= admin_services_path%>">Service</a>
        </li>

        <li>
            <a href="<%= admin_about_us_path%>">AboutU</a>
        </li>

        <li>
            <a href="<%= admin_products_path%>">Product</a>
        </li>
        <li>
            <a href="<%= admin_categories_path%>">Category</a>
        </li>
    </ul>
</div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        
        <!-- /#page-content-wrapper -->

   
   
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>

app/views/layouts/admin/admin_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
  <%= render "layouts/admin/head" %>
  </head>
  <body>
  <div id="wrapper">
    <%= render "layouts/admin/sidebar" %>
  	<%= render "layouts/admin/navbar" %>
    <%= yield %>
    <%= render "layouts/admin/footer" %>
  </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<%= render "layouts/head" %>
</head>
<body>
<%= render "layouts/navbar" %>
<%= yield %>
<%= render "layouts/footer" %>
</body>
</html>